compat: remove pre-patches for EOL kernel 3.2
Kernel 3.2 does no longer compile under newer gcc versions:
include/linux/compiler-gcc.h:105:1: fatal error: linux/compiler-gcc7.h: No such file or directory